# Generated by Django 3.1.3 on 2020-11-29 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree_table_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='is_root',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Tree_table',
        ),
        migrations.AddField(
            model_name='treetable',
            name='root',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='treeTable', to='tree_table_app.node'),
        ),
    ]
