# Generated by Django 3.1.3 on 2020-11-29 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=32767)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tree_table_app.node')),
            ],
        ),
        migrations.CreateModel(
            name='Tree_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('root', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tree_table', to='tree_table_app.node')),
            ],
        ),
    ]
