# Generated by Django 3.1.4 on 2020-12-17 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=32767)),
                ('is_root', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tree_table_app.node')),
            ],
        ),
        migrations.CreateModel(
            name='TreeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('jsonRepr', models.JSONField(default=None, null=True)),
                ('depth', models.PositiveIntegerField(default=0)),
                ('headers', models.JSONField(default=list)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('root', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='treeTable', to='tree_table_app.node')),
            ],
        ),
    ]
