# Generated by Django 3.1.4 on 2020-12-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_table_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='jsonRepr',
        ),
        migrations.AddField(
            model_name='treetable',
            name='jsonRepr',
            field=models.JSONField(default=None, null=True),
        ),
    ]
